### ISSUE TITLE
pangolin 

### ISSUE THREAD

**Issue by ahundt** [arpg/homebrew-coredev#1]
sorry if this is the wrong place but I couldn't put it directly in arpg/pangolin, and I do happen to be installing via homebrew. the arpg/pangolin version seems to be diverging more substantially from the upstream version. Can this potentially be resolved?

**Comment by crheckman** [comment]
We have a branch which tracks the upstream better named
feature/new_pangolin, and most of our apps are being ported over. It is
just a long process.

Thanks as always for your interest.
